import { ArrowLeft, ArrowRight, BookOpen, Eye, EyeOff, LockKeyhole, Mail } from 'lucide-react';
import { useState } from 'react';

export default function Login({ onSubmit, onRegister, onBack, notice }) {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [showPassword, setShowPassword] = useState(false);
    const [error, setError] = useState('');
    const submit = (event) => { event.preventDefault(); const message = onSubmit(email, password); if (message) setError(message); };
    return <main className="auth-page form-page"><section className="auth-visual compact-visual"><div className="auth-brand"><span className="auth-brand-mark"><BookOpen size={21} /></span><strong>Digital Library</strong></div><div className="login-quote"><p className="eyebrow light-eyebrow">Welcome back</p><h2>Pick up where<br /><em>you left off.</em></h2><div className="quote-rule" /><p>Your books and library card are waiting for you.</p></div><div className="visual-bookmark"><BookOpen size={18} /><span>READ • RETURN • REPEAT</span></div></section><section className="auth-form-panel"><button className="auth-back" onClick={onBack}><ArrowLeft size={16} /> Back to welcome</button><div className="form-heading"><div className="form-icon"><LockKeyhole size={20} /></div><p className="eyebrow">Student portal</p><h1>Welcome back</h1><p>Sign in to continue to your library.</p></div>{notice && <p className="form-success">{notice}</p>}<form className="auth-form" onSubmit={submit}><label>Email address<div className="field-wrap"><Mail size={17} /><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="student@library.com" autoComplete="email" /></div></label><label>Password<div className="field-wrap"><LockKeyhole size={17} /><input type={showPassword ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Enter your password" autoComplete="current-password" /><button type="button" className="field-action" onClick={() => setShowPassword((visible) => !visible)} aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></label>{error && <p className="form-error">{error}</p>}<button className="primary-button auth-submit" type="submit">Login <ArrowRight size={17} /></button></form><p className="form-switch">Don&apos;t have an account? <button onClick={onRegister}>Register now</button></p><p className="demo-hint">Demo: student@library.com / 123456</p></section></main>;
}
