import { AlertCircle, CheckCircle2, IndianRupee, ReceiptText, RotateCcw } from 'lucide-react';
import { calculateFine } from '../data/libraryData';
import { useState } from 'react';

export default function FineTracker({ books, onMarkReturned }) {
    const [filter, setFilter] = useState('all');
    const overdueBooks = books.filter((book) => book.status === 'Overdue');
    const fineRows = filter === 'paid' ? [] : overdueBooks;
    const totalFine = overdueBooks.reduce((sum, book) => sum + calculateFine(book.overdueDays || 0), 0);
    return <div className="page-content"><section className="page-title-row"><div><p className="eyebrow">Keep your account clear</p><h1>Fine Tracker</h1><p className="lead">Fines are calculated at ₹5 for every overdue day.</p></div><span className="fine-rule"><ReceiptText size={16} /> ₹5 / overdue day</span></section><section className="fine-summary-grid"><div className="fine-total-card"><div className="fine-card-icon"><IndianRupee size={20} /></div><span>Total Fine</span><strong>₹{totalFine}</strong><small>Across {overdueBooks.length} overdue books</small><div className="fine-card-line" /></div><SummaryCard icon={AlertCircle} label="Pending" value={`₹${totalFine}`} tone="orange" /><SummaryCard icon={CheckCircle2} label="Paid" value="₹0" tone="green" /></section><section className="panel table-panel"><div className="fine-tabs" role="tablist">{[['all', 'All'], ['pending', 'Pending'], ['paid', 'Paid']].map(([id, label]) => <button key={id} className={filter === id ? 'active' : ''} onClick={() => setFilter(id)} role="tab" aria-selected={filter === id}>{label}</button>)}</div><div className="table-summary"><div><p className="eyebrow">Outstanding payments</p><h2>Fine History</h2></div><span className="fine-status"><i /> Payment due</span></div><div className="table-wrap"><table><thead><tr><th>Book</th><th>Due Date</th><th>Overdue Days</th><th>Fine</th><th>Status</th><th>Action</th></tr></thead><tbody>{fineRows.length ? fineRows.map((book) => <tr key={book.id}><td><div className="table-book"><div className="mini-cover orange-cover"><IndianRupee size={14} /></div><strong>{book.title}</strong></div></td><td>{book.dueDate}</td><td>{book.overdueDays} days</td><td className="fine-cell">₹{calculateFine(book.overdueDays || 0)}</td><td><span className="badge overdue">Pending</span></td><td><button className="action-button" onClick={() => onMarkReturned(book.id)}><RotateCcw size={14} /> Mark Returned</button></td></tr>) : <tr><td colSpan="6"><div className="table-empty">No paid fines in this demo.</div></td></tr>}</tbody></table></div></section></div>;
}
function SummaryCard({ icon: Icon, label, value, tone }) { return <div className="summary-card"><div className={`summary-icon ${tone}`}><Icon size={18} /></div><span>{label}</span><strong>{value}</strong><small>As of today</small></div>; }
