import { BookOpen, Filter, RotateCcw, X } from 'lucide-react';
import { useState } from 'react';

const tabs = [['all', 'All'], ['borrowed', 'Currently Borrowed'], ['returned', 'Returned'], ['overdue', 'Overdue']];

export default function MyBooks({ books, onMarkReturned }) {
    const [activeTab, setActiveTab] = useState('all');
    const [selectedBook, setSelectedBook] = useState(null);
    const filteredBooks = books.filter((book) => activeTab === 'all' || (activeTab === 'borrowed' ? book.availability === 'Borrowed' : book.status.toLowerCase() === activeTab));
    return <div className="page-content"><section className="page-title-row"><div><p className="eyebrow">Personal shelf</p><h1>My Books</h1><p className="lead">Keep track of everything you have checked out.</p></div><button className="secondary-button" onClick={() => setActiveTab('all')}><Filter size={16} /> Show all books</button></section><section className="panel table-panel"><div className="book-tabs" role="tablist">{tabs.map(([id, label]) => <button key={id} className={activeTab === id ? 'active' : ''} onClick={() => setActiveTab(id)} role="tab" aria-selected={activeTab === id}>{label}<span>{id === 'all' ? books.length : id === 'borrowed' ? books.filter((book) => book.availability === 'Borrowed').length : books.filter((book) => book.status.toLowerCase() === id).length}</span></button>)}</div><div className="table-summary"><span><strong>{filteredBooks.length}</strong> titles in this view</span><span className="sync-label"><span className="live-dot" /> Updated just now</span></div><div className="table-wrap"><table><thead><tr><th>Book</th><th>Author</th><th>Borrow Date</th><th>Due Date</th><th>Status</th><th>Fine</th><th>Action</th></tr></thead><tbody>{filteredBooks.map((book) => <tr key={book.id}><td><div className="table-book"><div className="mini-cover"><BookOpen size={14} /></div><strong>{book.title}</strong></div></td><td>{book.author}</td><td>{book.borrowDate || '—'}</td><td>{book.dueDate || '—'}</td><td><span className={`badge status-${book.status.toLowerCase()}`}>{book.status}</span></td><td className="fine-cell">{book.fine ? `₹${book.fine}` : '—'}</td><td><div className="row-actions"><button className="details-button" onClick={() => setSelectedBook(book)}>View Details</button>{book.availability === 'Borrowed' && <button className="action-button" onClick={() => onMarkReturned(book.id)}><RotateCcw size={14} /> Return</button>}</div></td></tr>)}</tbody></table></div></section>{selectedBook && <BookModal book={selectedBook} onClose={() => setSelectedBook(null)} />}</div>;
}

function BookModal({ book, onClose }) {
    return <div className="modal-backdrop" onClick={onClose}><section className="book-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose} aria-label="Close details"><X size={18} /></button><div className="modal-cover"><BookOpen size={31} /></div><p className="category-label">{book.category}</p><h2>{book.title}</h2><p className="modal-author">{book.author}</p><div className="modal-grid"><span>Status<strong>{book.status}</strong></span><span>Due date<strong>{book.dueDate || 'Not checked out'}</strong></span><span>Fine<strong>{book.fine ? `₹${book.fine}` : 'No fine'}</strong></span></div><button className="primary-button auth-submit" onClick={onClose}>Done</button></section></div>;
}
